<?php
// include connection file 
include "dbconnect.php";
require('fpdf184/fpdf.php');


class PDF extends FPDF
{
   // Page header
function Header()
{
    
    // Logo
	$this->Image('logo/Solo.png',65,10,80);
	$this->Ln(10);
    $this->SetFont('Arial','B',13);
    // Move to the right
    $this->Cell(80);
	$this->Ln(10);
    // Line break
    $this->Ln(30);

}

// Page footer
function Footer()
{
    // Position at 1.5 cm from bottom
    $this->SetY(-15);
    // Arial italic 8
    $this->SetFont('Arial','I',8);
    // Page number
    $this->Cell(0,10,'Vinit Mohanbhai Dabhi - 8804874',0,0,'C');
}

}
 // Initialize PDF object
ob_clean();

$pdf = new PDF();
$pdf->AddPage();
$pdf->Ln(10);

$result = mysqli_query($conn, "SELECT UserName, ROUND(AVG(Total), 2) AS AvgSpend FROM OrderDetails GROUP BY UserName ORDER BY AvgSpend DESC");
$pdf->SetFont('Arial', 'B', 16);
$pdf->Cell(0, 10, 'Average money spent on online purchase', 0, 1, 'C');

$pdf->SetFont('Arial', 'B', 12);
$tableWidth = 120;


// Get current position
$currentY = $pdf->GetY();
$currentX = $pdf->GetX();

// Calculate table height
$tableHeight = 10 * mysqli_num_rows($result);

// Calculate center position
$pageWidth = $pdf->GetPageWidth();
$pageHeight = $pdf->GetPageHeight();
$leftMargin = ($pageWidth - $tableWidth) / 2;
$topMargin = ($pageHeight - $tableHeight) / 2;
$pdf->Ln(3);

// Set left and top margins
$pdf->SetLeftMargin($leftMargin);
$pdf->SetTopMargin($topMargin);
$pdf->Cell($tableWidth/2, 10, 'User Name', 1, 0, 'C');
$pdf->Cell($tableWidth/2, 10, 'Average Money Spent', 1, 1, 'C');

// Output table
while ($row = mysqli_fetch_assoc($result)) {
    $pdf->SetFont('Arial', '', 12);
    $pdf->Cell($tableWidth/2, 10, $row['UserName'], 1, 0, 'C');
    $pdf->Cell($tableWidth/2, 10, '$ '.$row['AvgSpend'], 1, 1, 'C');
}

// Reset left and top margins
$pdf->SetLeftMargin($currentX);
$pdf->SetTopMargin($currentY);
$pdf->Cell(115,60,'This file is generated by Vinit Dabhi member of Solo Squad ( a clothing store).',0,0,'C');

// Output PDF
$pdf->Output();


?>
